// Generated by skywork-cli website image import. Do not edit by hand.
export const IMAGES = {
  BRAND_DOT_LOGO: "/images/img_b0b1cfb03cde.png",
  BUSINESS_DOT_DATA: "/images/img_021051fca69c.jpg",
  BUSINESS_DOT_ESCO: "/images/img_b9f7786d0417.jpg",
  BUSINESS_DOT_RENEWABLE: "/images/img_714682f9a953.jpg",
  HOME_DOT_HERO: "/images/img_ccfac204b8f4.jpg",
  MEDIA_DOT_INSIGHT: "/images/img_993a9934b456.jpg",
  STORE_DOT_BALCONY: "/images/img_f9285b14f8f4.jpg",
} as const;
